version: '3'

services:

  api:
    build: .
    command: "flask run"
    environment:
      - FLASK_APP=spell_checker
      - FLASK_RUN_HOST=0.0.0.0
    ports:
      - "31337:5000"
    volumes:
      - .:/spell-checker
  
  redis_db:
    image: "redis:alpine"

  redis_seed:
    build: .
    command: "python scripts/populate_redis.py --host redis_db"
    depends_on:
      - redis_db
